### ISSUE TITLE
Take-Home Test Goals

### ISSUE THREAD

**Issue by codekeyz** [keezysilencer/achieve-test#1]
## Tasks

- [x] View Assets from CoinCap
- [x] Add Support for Searching Assets

- [x] For each Asset, you're to display the `name`, `priceUsd` & `marketCapUsd` using a ListTile.
- [x] Load More Assets when Assets Lists is Scrolled Downwards

- [x] Add Tests for Core Components

**Comment by codekeyz** [comment]
@keezysilencer I've added the tasks you're to complete. Do tick them off as your push your code. Good luck 🚀

**Comment by keezysilencer** [comment]
@codekeyz I am done

**Comment by codekeyz** [comment]
@keezysilencer Great work 🔥 . Slight thingy, i don't think you added the scroll to load more behaviour.

**Comment by codekeyz** [comment]
I think you missed the search feature too. 🤔

**Comment by keezysilencer** [comment]
Ohkay, I just verified. I was reading from the version 1 of the api documentation.

**Comment by keezysilencer** [comment]
@codekeyz I have made the necessary changes
